spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agroecologiaiot
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # update hace que la DB se cree y se actualice con los cambios cuando ejecutamos el proyecto.
    #  naming:
    #    strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
